name: hadith-rag
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.2=pyhc872135_1
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - aiosqlite==0.21.0
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - banks==2.2.0
      - beautifulsoup4==4.14.2
      - black==25.9.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorama==0.4.6
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - dirtyjson==1.0.8
      - distro==1.9.0
      - fastapi==0.121.1
      - filetype==1.2.0
      - flake8==7.3.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - greenlet==3.2.4
      - griffe==1.14.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h2==4.3.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - hyperframe==6.1.0
      - idna==3.11
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - llama-cloud==0.1.35
      - llama-cloud-services==0.6.54
      - llama-index==0.14.7
      - llama-index-cli==0.5.3
      - llama-index-core==0.14.7
      - llama-index-embeddings-ollama==0.8.3
      - llama-index-embeddings-openai==0.5.1
      - llama-index-indices-managed-llama-cloud==0.9.4
      - llama-index-instrumentation==0.4.2
      - llama-index-llms-ollama==0.9.0
      - llama-index-llms-openai==0.6.7
      - llama-index-readers-file==0.5.4
      - llama-index-readers-llama-parse==0.5.1
      - llama-index-vector-stores-qdrant==0.8.6
      - llama-index-workflows==2.11.1
      - llama-parse==0.6.54
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - markdownify==1.2.0
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - mccabe==0.7.0
      - mdurl==0.1.2
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - nest-asyncio==1.6.0
      - networkx==3.5
      - nltk==3.9.2
      - numpy==2.3.4
      - ollama==0.6.0
      - openai==1.109.1
      - packaging==25.0
      - pandas==2.2.3
      - pathspec==0.12.1
      - pillow==12.0.0
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - portalocker==3.2.0
      - propcache==0.4.1
      - protobuf==6.33.0
      - pycodestyle==2.14.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-settings==2.11.0
      - pyflakes==3.4.0
      - pygments==2.19.2
      - pypdf==6.2.0
      - pypdf2==3.0.1
      - pytest==8.4.2
      - pytest-asyncio==1.2.0
      - python-dateutil==2.9.0.post0
      - python-docx==1.2.0
      - python-dotenv==1.2.1
      - pytokens==0.3.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - qdrant-client==1.15.1
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - starlette==0.49.3
      - striprtf==0.0.26
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - tqdm==4.67.1
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wrapt==1.17.3
      - yarl==1.22.0
prefix: /opt/anaconda3/envs/hadith-rag
